{\rtf1\ansi\ansicpg1252\cocoartf2757
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 Training set contains 165034 rows and 14 columns.\
Number of duplicate rows: 0\
Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',\
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',\
       'Exited'],\
      dtype='object')\
<class 'pandas.core.frame.DataFrame'>\
RangeIndex: 165034 entries, 0 to 165033\
Data columns (total 11 columns):\
 #   Column           Non-Null Count   Dtype  \
---  ------           --------------   -----  \
 0   CreditScore      165034 non-null  int64  \
 1   Geography        165034 non-null  object \
 2   Gender           165034 non-null  object \
 3   Age              165034 non-null  float64\
 4   Tenure           165034 non-null  int64  \
 5   Balance          165034 non-null  float64\
 6   NumOfProducts    165034 non-null  int64  \
 7   HasCrCard        165034 non-null  float64\
 8   IsActiveMember   165034 non-null  float64\
 9   EstimatedSalary  165034 non-null  float64\
 10  Exited           165034 non-null  int64  \
dtypes: float64(5), int64(4), object(2)\
memory usage: 13.9+ MB\
                    count           mean  ...          75%        max\
CreditScore      165034.0     656.454373  ...     710.0000     850.00\
Age              165034.0      38.125888  ...      42.0000      92.00\
Tenure           165034.0       5.020353  ...       7.0000      10.00\
Balance          165034.0   55478.086689  ...  119939.5175  250898.09\
NumOfProducts    165034.0       1.554455  ...       2.0000       4.00\
HasCrCard        165034.0       0.753954  ...       1.0000       1.00\
IsActiveMember   165034.0       0.497770  ...       1.0000       1.00\
EstimatedSalary  165034.0  112574.822734  ...  155152.4675  199992.48\
Exited           165034.0       0.211599  ...       0.0000       1.00\
\
[9 rows x 8 columns]\
Continuous:  Age, CreditScore, Balance, EstimatedSalary\
Categorical:  Geography, Gender, Tenure, NumOfProducts, HasCrCard, IsActiveMember\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:243: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x='Exited', data=train_df, palette=plot_colors, ax=ax)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:255: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax.set_xticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: UserWarning: The palette list has more values (11) than needed (3), which may not be intended.\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: UserWarning: The palette list has more values (11) than needed (4), which may not be intended.\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:316: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.countplot(x=column, data=train_df, palette=plot_colors_cat)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: UserWarning: The palette list has more values (11) than needed (3), which may not be intended.\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: UserWarning: The palette list has more values (11) than needed (4), which may not be intended.\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:106: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax1.set_xticklabels(['No', 'Yes'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:107: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_xticklabels(['No', 'Yes'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:99: UserWarning: The palette list has more values (11) than needed (2), which may not be intended.\
  sns.barplot(x=feature, y='Exited', data=train_df, palette=plot_colors_cat, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:106: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax1.set_xticklabels(['No', 'Yes'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:107: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_xticklabels(['No', 'Yes'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:75: FutureWarning: \
\
Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\
\
  sns.boxplot(x=feature, y='Exited', data=df_boxplot, palette=plot_colors, ax=ax2)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:77: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.\
  ax2.set_yticklabels(['Retained', 'Churned'])\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
Initial Models (Recall):\
   Gaussian Naive Bayes: 0.87\
   Logistic Regression: 0.74\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\
  warnings.warn(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\
\
Increase the number of iterations (max_iter) or scale the data as shown in:\
    https://scikit-learn.org/stable/modules/preprocessing.html\
Please also refer to the documentation for alternative solver options:\
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\
  n_iter_i = _check_optimize_result(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
30 fits failed out of a total of 120.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
30 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper\
    return fit_method(estimator, *args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1172, in fit\
    solver = _check_solver(self.solver, self.penalty, self.dual)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 67, in _check_solver\
    raise ValueError(\
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan 0.71702315 0.75490552 0.75821037        nan 0.79287268\
 0.73822782 0.78105987        nan 0.8005123  0.75303037 0.78138266\
        nan 0.80139619 0.73746696 0.78159018        nan 0.8013347\
 0.7376898  0.78208973        nan 0.80129627 0.75214653 0.78158249]\
  warnings.warn(\
\
 Logistic Regression\
-------------------------------\
   Best Score (recall): 0.801\
   Best Parameters: \
      C: 0.1\
      max_iter: 100\
      penalty: l1\
      solver: liblinear\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
2 fits failed out of a total of 25.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
2 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper\
    return fit_method(estimator, *args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1221, in fit\
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/svm/_base.py", line 1174, in _fit_liblinear\
    raise ValueError(\
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\
  warnings.warn(\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
180 fits failed out of a total of 360.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
72 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1344, in wrapper\
    estimator._validate_params()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params\
    validate_parameter_constraints(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints\
    raise InvalidParameterError(\
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among \{'log2', 'sqrt'\} or None. Got 'auto' instead.\
\
--------------------------------------------------------------------------------\
108 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1344, in wrapper\
    estimator._validate_params()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params\
    validate_parameter_constraints(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints\
    raise InvalidParameterError(\
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among \{'sqrt', 'log2'\} or None. Got 'auto' instead.\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan\
        nan        nan        nan 0.85023079 0.85023079 0.85014625\
 0.85041525 0.85041525 0.85041525 0.8506535  0.8506535  0.8506535\
        nan        nan        nan        nan        nan        nan\
        nan        nan        nan 0.8520907  0.8520907  0.8523059\
 0.85269018 0.85269018 0.85269018 0.85289001 0.85289001 0.85289001\
        nan        nan        nan        nan        nan        nan\
        nan        nan        nan 0.85088407 0.85088407 0.85093787\
 0.85086101 0.85086101 0.85086101 0.85093018 0.85093018 0.85093018\
        nan        nan        nan        nan        nan        nan\
        nan        nan        nan 0.85310521 0.85310521 0.85308984\
 0.85279778 0.85279778 0.85279778 0.85330504 0.85330504 0.85330504]\
  warnings.warn(\
\
 Random Forest\
-------------------------------\
   Best Score (recall): 0.853\
   Best Parameters: \
      bootstrap: False\
      criterion: gini\
      max_depth: 6\
      max_features: sqrt\
      min_samples_leaf: 5\
      min_samples_split: 2\
      n_estimators: 100\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
80 fits failed out of a total of 240.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
68 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1344, in wrapper\
    estimator._validate_params()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params\
    validate_parameter_constraints(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints\
    raise InvalidParameterError(\
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of GradientBoostingClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among \{'log2', 'sqrt'\} or None. Got 'auto' instead.\
\
--------------------------------------------------------------------------------\
12 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1344, in wrapper\
    estimator._validate_params()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params\
    validate_parameter_constraints(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints\
    raise InvalidParameterError(\
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of GradientBoostingClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among \{'sqrt', 'log2'\} or None. Got 'auto' instead.\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan\
        nan        nan 0.83830266 0.8382258  0.83830266 0.8382258\
 0.83830266 0.8382258  0.83830266 0.8382258  0.85690932 0.8569247\
 0.85690932 0.8569247  0.85690932 0.8569247  0.85690932 0.8569247\
        nan        nan        nan        nan        nan        nan\
        nan        nan 0.8437441  0.84391318 0.8437441  0.84391318\
 0.8437441  0.84391318 0.8437441  0.84391318 0.84650328 0.84622658\
 0.84650328 0.84622658 0.84623429 0.84628806 0.84623429 0.84628806]\
  warnings.warn(\
\
 Gradient Boosting Classifier\
-------------------------------\
   Best Score (recall): 0.857\
   Best Parameters: \
      learning_rate: 0.001\
      max_depth: 3\
      max_features: None\
      min_samples_leaf: 3\
      min_samples_split: 5\
      n_estimators: 600\
      n_iter_no_change: 20\
      subsample: 0.75\
      tol: 0.01\
      validation_fraction: 0.2\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
2 fits failed out of a total of 25.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
2 fits failed with the following error:\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper\
    return fit_method(estimator, *args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 665, in fit\
    y = self._encode_y(y=y, sample_weight=None)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 1520, in _encode_y\
    raise ValueError(\
ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\
  warnings.warn(\
\
 XGBoost Classifier\
-------------------------------\
   Best Score (recall): 0.839\
   Best Parameters: \
      colsample_bytree: 0.5\
      gamma: 0.1\
      learning_rate: 0.01\
      max_depth: 4\
      min_child_weight: 1\
      n_estimators: 50\
      reg_alpha: 1\
      reg_lambda: 1\
      subsample: 0.5\
/opt/anaconda3/envs/BankCustomerChurnPrediction/Script.py:184: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.\
  fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))\
Soft Voting\
-----------------\
  Recall:  0.854\
/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning: \
2 fits failed out of a total of 25.\
The score on these train-test partitions for these parameters will be set to nan.\
If these failures are not expected, you can try to debug them by setting error_score='raise'.\
\
Below are more details about the failures:\
--------------------------------------------------------------------------------\
2 fits failed with the following error:\
joblib.externals.loky.process_executor._RemoteTraceback: \
"""\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call\
    return func()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__\
    return [func(*args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>\
    return [func(*args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 129, in __call__\
    return self.function(*args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_base.py", line 36, in _fit_single_estimator\
    estimator.fit(X, y)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper\
    return fit_method(estimator, *args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 665, in fit\
    y = self._encode_y(y=y, sample_weight=None)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 1520, in _encode_y\
    raise ValueError(\
ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.\
"""\
\
The above exception was the direct cause of the following exception:\
\
Traceback (most recent call last):\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score\
    estimator.fit(X_train, y_train, **fit_params)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper\
    return fit_method(estimator, *args, **kwargs)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_voting.py", line 351, in fit\
    return super().fit(X, transformed_y, sample_weight)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/ensemble/_voting.py", line 85, in fit\
    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 67, in __call__\
    return super().__call__(iterable_with_config)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__\
    return output if self.return_generator else list(output)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs\
    yield from self._retrieve()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve\
    self._raise_error_fast()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast\
    error_job.get_result(self.timeout)\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result\
    return self._return_or_raise()\
  File "/opt/anaconda3/envs/BankCustomerChurnPrediction/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise\
    raise self._result\
ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.\
\
  warnings.warn(some_fits_failed_message, FitFailedWarning)\
}